version: "3.7"
services:
  web-server:
    container_name: petrikor
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - ".:/var/www/html"
    ports:
      - "8080:80"